name: Build and Release

on:
  push:
    branches:
      - develop
      - release
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

    # Step para checkout do repositório principal
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
        submodules: 'true'  # Certifica-se de que os submódulos sejam verificados

    # Step para garantir que os submódulos estão na branch correta
    - name: Checkout submodules to correct branch
      run: |
        $BRANCH_NAME = $Env:GITHUB_REF.Split('/')[-1]
        git submodule foreach "git checkout $BRANCH_NAME && git pull origin $BRANCH_NAME"
        
    # Setup .NET SDK
    - name: Install .NET SDK
      run: choco install dotnet-8.0-sdk -y --no-progress
      shell: pwsh

    # Setup .NET Framework
    - name: Install .NET Framework and required workloads
      run: |
        choco install visualstudio2022community -y --no-progress
        choco install visualstudio2022-workload-manageddesktop -y --no-progress
        choco install dotnet-6.0-sdk -y --no-progress
      shell: pwsh
      
    # Check .NET available SDKs
    - name: Ensure .NET SDK is available for MSBuild
      run: |
        echo "##[debug] .NET SDKs disponíveis:"
        dotnet --list-sdks
      shell: pwsh

    # Build .NET solution
    - name: Build .NET solution
      run: |
        nuget restore "prs_app/ProRacingSoftware.sln"
        & "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" "prs_app/ProRacingSoftware.sln" /p:Configuration=Release /p:Platform="Any CPU"
        dotnet publish prs_service\Prs.App.Service\Prs.App.Service.csproj -c Release -r win-x64 --self-contained true -o prs_app\ProRacingSoftware\bin\Release\service

    # List files in prs_release/beta
    - name: List files in prs_release/beta
      run: |
        dir prs_app\ProRacingSoftware\bin\Release
