name: Build and Release

on:
  push:
    branches:
      - develop
      - release
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

    # Step para checkout do repositório principal
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
        submodules: 'true'  # Certifica-se de que os submódulos sejam verificados

    - name: Set common env
      shell: pwsh
      run: |
        echo "PROJECT_NAME=hg_app" >> $GITHUB_ENV
        echo "RELEASE_DIRECTORY=./release" >> $GITHUB_ENV
        echo "RELEASE_CHANGELOG=changes.md" >> $GITHUB_ENV

    - name: Set alpha env
      if: ${{ github.ref == 'refs/heads/develop' }}
      shell: pwsh
      run: |
        echo "RELEASE_PRE=true" >> $GITHUB_ENV
        echo "RELEASE_KIND=pre-release" >> $GITHUB_ENV

    - name: Set beta env
      if: ${{ github.ref == 'refs/heads/release' }}
      shell: pwsh
      run: |
        echo "RELEASE_PRE=true" >> $GITHUB_ENV
        echo "RELEASE_KIND=pre-release" >> $GITHUB_ENV

    - name: Set release env
      if: ${{ github.ref == 'refs/heads/main' }}
      shell: pwsh
      run: |
        echo "RELEASE_PRE=false" >> $GITHUB_ENV
        echo "RELEASE_KIND=release" >> $GITHUB_ENV

    # Define variáveis de ambiente
    - name: Set common environment variables
      shell: pwsh
      run: |
        echo "ZIP_FILENAME=prs_app" >> $env:GITHUB_ENV
        echo "RELEASE_DIRECTORY=prs_app\ProRacingSoftware\bin\Release" >> $env:GITHUB_ENV
        echo "RELEASE_CHANGELOG=prs_app\changes.md" >> $env:GITHUB_ENV

    # Fix submodule branches
    - name: Checkout submodules to correct branch
      shell: pwsh
      run: |
        $BRANCH_NAME = $Env:GITHUB_REF.Split('/')[-1]
        git submodule foreach "git checkout $BRANCH_NAME && git pull origin $BRANCH_NAME"
        
    # Setup .NET Framework
    - name: Install .NET Framework and required workloads
      shell: pwsh
      run: |
        choco install visualstudio2022community -y --no-progress
        choco install visualstudio2022-workload-manageddesktop -y --no-progress
        choco install dotnet-6.0-sdk -y --no-progress

    # Build .NET solution
    - name: Build .NET solution
      shell: pwsh
      run: |
        nuget restore "prs_app/ProRacingSoftware.sln"
        & "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" "prs_app/ProRacingSoftware.sln" /p:Configuration=Release /p:Platform="Any CPU"
        dotnet publish prs_service\Prs.App.Service\Prs.App.Service.csproj -c Release -r win-x64 --self-contained true -o prs_app\ProRacingSoftware\bin\Release\service

    # Set version
    - name: Set Version
      shell: pwsh
      run: |
        $versionString = (Get-Item "prs_app\ProRacingSoftware\bin\Release\ProRacingSoftware.exe").VersionInfo.FileVersion
        echo "RELEASE_VERSION=$versionString" >> $env:GITHUB_ENV

    # Create zip file
    - name: Archive build
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        directory: ${{ env.RELEASE_DIRECTORY }}
        filename: ${{ env.ZIP_FILENAME }}.zip
    
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Create and push tag
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git tag v${{ env.RELEASE_VERSION }}
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git v${{ env.RELEASE_VERSION }}

    # Create release
    - name: Create release
      if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main' }}
      uses: softprops/action-gh-release@v1
      with:
        prerelease: ${{ env.RELEASE_PRE }}
        body_path: ${{ github.workspace }}/${{ env.RELEASE_CHANGELOG }}
        name: ${{ env.RELEASE_KIND }} ${{ env.RELEASE_VERSION }}
        tag_name: ${{ env.RELEASE_VERSION }}
        files: |
          ./${{ env.RELEASE_DIRECTORY }}/${{ env.ZIP_FILENAME }}.zip
