name: Build and Release

on:
  push:
    branches:
      - develop
      - release
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:

    # Step para checkout do repositório principal
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
        submodules: 'true'  # Certifica-se de que os submódulos sejam verificados

    # Step para garantir que os submódulos estão na branch correta
    - name: Checkout submodules to correct branch
      run: |
        $BRANCH_NAME = $Env:GITHUB_REF.Split('/')[-1]
        git submodule foreach "git checkout $BRANCH_NAME && git pull origin $BRANCH_NAME"
        
    # Setup .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    # Setup .NET Framework
    - name: Install .NET Framework build tools
      run: |
        choco install visualstudio2022buildtools -y --no-progress
        choco install visualstudio2022-workload-manageddesktop -y --no-progress
      shell: pwsh
        

    # Verifique o diretório atual para garantir o caminho correto
    - name: Verify directory structure
      run: |
        tree

    # Build .NET solution
    - name: Build .NET solution
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" prs_app/ProRacingSoftware.sln /p:Configuration=Release /p:Platform="Any CPU"

    # List files in prs_release/beta
    - name: List files in prs_release/beta
      run: |
        dir prs_release\beta
